

XVFB_PID=""
cleanup() {
  # kill Xvfb if running
  [[ -n "$XVFB_PID" ]] && kill "$XVFB_PID" 2>/dev/null
  rm -f "$TMP_WAV" "$TERMVID.lock" 2>/dev/null
}


die() {
	local code=${2:-1}
	echo "${RED}Error: $1${RESET}" >&2
	exit "$code"
}

warn() {
	echo "${YELLOW}Warning: $1${RESET}" >&2
}

ensure_file_exists() {
	[[ -f "$1" ]] || die "File does not exist: $1"
}

ensure_file_readable() {
    ensure_file_exists "$1" && [[ -r "$1" ]] || die "File not readable: $1"
}

# Only Debian help for now
check_environment() {
	local tools=(openmpt123 ffmpeg sox convert xterm Xvfb xwininfo)
	for tool in "${tools[@]}"; do
		command -v "$tool" >/dev/null || {
			echo "${RED}Missing: $BOLD$tool$RESET"
			echo -en "If you're on Debian/Ubuntu/Mint, install packages with"
			echo "  sudo apt install openmpt123 ffmpeg sox imagemagick xterm xvfb x11-utils"
			exit 1
		}
	done
}

# the output of this function can be used to
# easily define a new template
print_settings() {
cat <<EOT
# mod2vid template
# Name:
# Author:
# Date:

# Terminal Settings
TERMINAL_COLS=$TERMINAL_COLS
TERMINAL_ROWS=$TERMINAL_ROWS
TERM_THEME=$TERM_THEME
TERM_FONT_SIZE=$TERM_FONT_SIZE
SUPPRESS_AUDIO=$SUPPRESS_AUDIO
# openmpt background: track info (openmpt123 --info)
TITLE_FONT_MONO="$TITLE_FONT_MONO"

# Background Settings
BACKGROUND_COLOR="$BACKGROUND_COLOR"
BACKGROUND_IMAGE="$BACKGROUND_IMAGE"
EOT
if [[ -n "$BACKGROUND_IMAGE_POOL" ]]; then
echo "BACKGROUND_IMAGE_POOL=("
for image in "${BACKGROUND_IMAGE_POOL[@]}"; do
  echo "  \"$image\""
done
echo ")"
fi
cat <<EOT

# Title Settings
TITLE_FONT_FILE="$TITLE_FONT_FILE"
TITLE_FONT_SIZE=$TITLE_FONT_SIZE
TITLE_FONT_COLOR="$TITLE_FONT_COLOR"
TITLE_TEXT_POS_X="$TITLE_TEXT_POS_X"
TITLE_TEXT_POS_Y="$TITLE_TEXT_POS_Y"
TITLE_TEXT="$TITLE_TEXT_ORIG"
TITLE_SHADOW_X=$TITLE_SHADOW_X
TITLE_SHADOW_Y=$TITLE_SHADOW_Y

# Frequency View
SHOW_FREQ=$SHOW_FREQ
FREQ_MODE=$FREQ_MODE
FREQ_FSCALE=$FREQ_FSCALE
FREQ_ASCALE=$FREQ_ASCALE
FREQ_COL_1=$FREQ_COL_1
FREQ_COL_2=$FREQ_COL_2
FREQ_COL_ALPHA=$FREQ_COL_ALPHA
FREQ_WIDTH=$FREQ_WIDTH
FREQ_HEIGHT=$FREQ_HEIGHT
FREQ_POS_X=$FREQ_POS_X
FREQ_POS_Y=$FREQ_POS_Y

# Waves
SHOW_WAVES=$SHOW_WAVES
WAVES_COLOR=$WAVES_COLOR
WAVES_MODE=$WAVES_MODE
WAVES_SIZE=$WAVES_SIZE
WAVES_WIDTH=$WAVES_WIDTH
WAVES_HEIGHT=$WAVES_HEIGHT
WAVES_POS_X=$WAVES_POS_X
WAVES_POS_Y=$WAVES_POS_Y

# Spectrum
SHOW_SPECTRUM=$SHOW_SPECTRUM
SPECTRUM_WIDTH=$SPECTRUM_WIDTH
SPECTRUM_HEIGHT=$SPECTRUM_HEIGHT
SPECTRUM_POS_X=$SPECTRUM_POS_X
SPECTRUM_POS_Y=$SPECTRUM_POS_Y
SPECTRUM_COLOR=$SPECTRUM_COLOR

# Patterns
PATTERN_WIDTH=$PATTERN_WIDTH
PATTERN_HEIGHT=$PATTERN_HEIGHT
PATTERN_OFFSET_X=$PATTERN_OFFSET_X
PATTERN_OFFSET_Y=$PATTERN_OFFSET_Y
PATTERN_GAMMA_R=$PATTERN_GAMMA_R
PATTERN_GAMMA_G=$PATTERN_GAMMA_G
PATTERN_GAMMA_B=$PATTERN_GAMMA_B
PATTERN_COLOR_BOOST_R=$PATTERN_COLOR_BOOST_R
PATTERN_COLOR_BOOST_G=$PATTERN_COLOR_BOOST_G
PATTERN_COLOR_BOOST_B=$PATTERN_COLOR_BOOST_B
PATTERN_GLOW_RADIUS=$PATTERN_GLOW_RADIUS
PATTERN_GLOW_OPACITY=$PATTERN_GLOW_OPACITY
PATTERN_GLOW_MODE=$PATTERN_GLOW_MODE

NO_TRACK_INFO=$NO_TRACK_INFO

# Subtitle
SUBTITLE_FILE="$SUBTITLE_FILE"

# Logo
LOGO_FILE="$LOGO_FILE"
LOGO_SIZE=$LOGO_SIZE
LOGO_POSITION=$LOGO_POSITION
EOT

}
